/**
 * Brand Service
 * 
 * Handles tenant branding configuration for PDF exports and other branded content.
 * Falls back to RatePro defaults when tenant branding is not configured.
 */

const Tenant = require('../../models/Tenant');
const path = require('path');

// RatePro default branding
const DEFAULT_BRANDING = {
    companyName: 'RatePro',
    logoPath: path.join(__dirname, '../../assets/logo-default.png'),
    primaryColor: '#1fdae4',     // RatePro teal
    secondaryColor: '#0d6efd',   // Bootstrap primary blue
    accentColor: '#6c757d',      // Gray accent
    textColor: '#333333',
    headerBgColor: '#ffffff',
    footerText: 'Generated by RatePro Analytics Platform',
    website: 'https://ratepro.com',
};

/**
 * Get branding configuration for a tenant
 * Falls back to default RatePro branding if not configured
 */
async function getTenantBranding(tenantId) {
    try {
        if (!tenantId) {
            return DEFAULT_BRANDING;
        }

        const tenant = await Tenant.findById(tenantId)
            .select('name contactEmail website branding logo')
            .lean();

        if (!tenant) {
            return DEFAULT_BRANDING;
        }

        // Merge tenant data with defaults
        const branding = {
            companyName: tenant.name || DEFAULT_BRANDING.companyName,
            logoPath: tenant.branding?.logoPath || tenant.logo?.url || DEFAULT_BRANDING.logoPath,
            logoUrl: tenant.logo?.url || null,
            primaryColor: tenant.branding?.primaryColor || DEFAULT_BRANDING.primaryColor,
            secondaryColor: tenant.branding?.secondaryColor || DEFAULT_BRANDING.secondaryColor,
            accentColor: tenant.branding?.accentColor || DEFAULT_BRANDING.accentColor,
            textColor: tenant.branding?.textColor || DEFAULT_BRANDING.textColor,
            headerBgColor: tenant.branding?.headerBgColor || DEFAULT_BRANDING.headerBgColor,
            footerText: tenant.branding?.footerText || `Generated for ${tenant.name}`,
            website: tenant.website || DEFAULT_BRANDING.website,
            tenantId: tenant._id,
        };

        return branding;
    } catch (error) {
        console.error('Error fetching tenant branding:', error);
        return DEFAULT_BRANDING;
    }
}

/**
 * Parse hex color to RGB object
 */
function hexToRgb(hex) {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return result ? {
        r: parseInt(result[1], 16),
        g: parseInt(result[2], 16),
        b: parseInt(result[3], 16),
    } : { r: 0, g: 0, b: 0 };
}

/**
 * Check if a color is light or dark (for contrast decisions)
 */
function isLightColor(hex) {
    const rgb = hexToRgb(hex);
    const luminance = (0.299 * rgb.r + 0.587 * rgb.g + 0.114 * rgb.b) / 255;
    return luminance > 0.5;
}

module.exports = {
    getTenantBranding,
    hexToRgb,
    isLightColor,
    DEFAULT_BRANDING,
};
